name: Discord Push Notification

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send push notification to Discord
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'New push to **${{ github.repository }}** on `${{ github.ref_name }}` by **${{ github.actor }}**'
