name: Discord Push Notification

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send push notification to Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "New push to **${{ github.repository }}** on `${{ github.ref_name }}` by **${{ github.actor }}**"
